### ISSUE TITLE
latency not quite right

### ISSUE THREAD

**Issue by weixingsun** [DhruvDh/memory-bench#1]
Hi there

I am running on my box, but it gives me some incredible low latency :
Would you please give me some advices ? and what is your rust versions? 

cargo build --release --target=x86_64-unknown-linux-musl
target/x86_64-unknown-linux-musl/release/latency
8B:     0.0021 nanoseconds
16B:    0.00025 nanoseconds
32B:    0.00015 nanoseconds
64B:    0.0001 nanoseconds
128B:   0.00005 nanoseconds
256B:   0.000034375 nanoseconds
512B:   0.000025 nanoseconds
1024B:  0.000022734375 nanoseconds
2KB:    0.000019960937 nanoseconds
4KB:    0.000019570312 nanoseconds
8KB:    0.000018984376 nanoseconds
16KB:   0.000018637695 nanoseconds
32KB:   0.000018564453 nanoseconds
64KB:   0.000018699951 nanoseconds
128KB:  0.000019158326 nanoseconds
256KB:  0.00018540649 nanoseconds
512KB:  0.000204393 nanoseconds
1024KB: 0.018964844 nanoseconds
2MB:    0.010732193 nanoseconds
4MB:    0.17327575 nanoseconds
8MB:    0.2256525 nanoseconds
16MB:   0.2502429 nanoseconds
32MB:   0.26119035 nanoseconds
64MB:   0.27844 nanoseconds
128MB:  0.279684 nanoseconds
256MB:  0.28943986 nanoseconds
512MB:  0.2912181 nanoseconds
1024MB: 0.29017955 nanoseconds
2GB:    0.29167056 nanoseconds
4GB:    0.2909394 nanoseconds
8GB:    0.29110348 nanoseconds
16GB:   0.29113573 nanoseconds

cargo build --release --target=x86_64-unknown-linux-gnu
target/x86_64-unknown-linux-gnu/release/latency
8B:     0.0009 nanoseconds
16B:    0.00025 nanoseconds
32B:    0.000175 nanoseconds
64B:    0.0001 nanoseconds
128B:   0.000056874997 nanoseconds
256B:   0.000040625 nanoseconds
512B:   0.000025 nanoseconds
1024B:  0.000021875 nanoseconds
2KB:    0.000022304688 nanoseconds
4KB:    0.000021328126 nanoseconds
8KB:    0.000022802735 nanoseconds
16KB:   0.000023188475 nanoseconds
32KB:   0.000019787598 nanoseconds
64KB:   0.000020375977 nanoseconds
128KB:  0.000020986328 nanoseconds
256KB:  0.00031880493 nanoseconds
512KB:  0.00031840667 nanoseconds
1024KB: 0.018135529 nanoseconds
2MB:    0.017612686 nanoseconds
4MB:    0.29340285 nanoseconds
8MB:    0.64067847 nanoseconds
16MB:   0.76659465 nanoseconds
32MB:   0.7826302 nanoseconds
64MB:   0.7822408 nanoseconds
128MB:  0.7812073 nanoseconds
256MB:  0.746878 nanoseconds
512MB:  0.75854707 nanoseconds
1024MB: 0.77676314 nanoseconds
2GB:    0.77334344 nanoseconds
4GB:    0.77235824 nanoseconds
8GB:    0.77355194 nanoseconds
16GB:   0.7819588 nanoseconds

**Comment by DhruvDh** [comment]
I just tried this out, on `rustc 1.50.0-nightly (fe982319a 2020-11-19)` for the `x86_64-pc-windows-msvc` target, and it works fine for me. 

The only change I made was in `.cargo/config` I removed the `linux-musl` target. I wrote this to run on an old Xeon CPU at my university's cluster. You might also want to edit `.cargo/config` and change `target-cpu` to `native`.

I've pushed this changes to `.cargo/config` to master.

Here is the output on my laptop (it worked fine before the changes as well) -

```
    Finished release [optimized] target(s) in 4.31s
     Running `target\release\latency.exe`
[src\main.rs:149] &sum = 1000000
8B:     7.7550006 nanoseconds
[src\main.rs:149] &sum = 2000000
16B:    5.3375 nanoseconds
[src\main.rs:149] &sum = 4000000
32B:    6.2965 nanoseconds
[src\main.rs:149] &sum = 8000000
64B:    5.357875 nanoseconds
[src\main.rs:149] &sum = 16000000
128B:   6.4511876 nanoseconds
[src\main.rs:149] &sum = 32000000
256B:   8.59125 nanoseconds
[src\main.rs:149] &sum = 64000000
512B:   9.689375 nanoseconds
[src\main.rs:149] &sum = 128000000
1024B:  12.143851 nanoseconds
[src\main.rs:149] &sum = 256000000
2KB:    11.484445 nanoseconds
[src\main.rs:149] &sum = 512000000
4KB:    11.39809 nanoseconds
[src\main.rs:149] &sum = 1024000000
8KB:    20.856596 nanoseconds
error: process didn't exit successfully: `target\release\latency.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
````
I Ctrl-C'ed to exit early because I did not want to wait for it to finish. Most likely reads are being optimized out for you. You might want to sprinkle a few `dbg!(sum);` at the end of every loop in `do_read` to make sure compiler actually computes `sum`.

If values are still too low, it is likely compiler is noticing that nums is just a bunch of ones. Even though this is a linked list and it should not be possible for the compiler to do so, try changing this -

```rust
    (0..size).for_each(|_| {
        nums.push(1u64);
    });
```

To be a random number each time instead of one. Just make sure it's a 64 bit integer.

**Comment by weixingsun** [comment]
thanks your prompt reply, I didn't notice commented out the line 146: dbg!(sum) and caused this problem. 
I thought it was a debugging log, cheers
